// GENERATED by tools/solve_fold.mjs — do not hand-edit, re-run the tool.
//
// The folded-wing pose, as one local quaternion per wing bone, in the same
// glTF frame three.js loads. dragonrig.js slerps each bone from its bind
// rotation to the entry here, scaled by how folded he is.
//
// Solved rather than authored: see tools/solve_fold.mjs. Bone lengths, the
// ribcage and the floor are hard constraints, so this pose cannot stretch his
// arm, pass a wing through his chest, or hang it through the ground — which is
// exactly what hand-tuned fold angles kept doing.

export const FOLD_POSE = {
  "Wing_Shoulder.L": [
    -0.56536,
    -0.00185,
    0.46205,
    0.68329
  ],
  "Wing_UpperArm.L": [
    0.24658,
    0.01642,
    0.50809,
    0.82509
  ],
  "Wing_Forearm.L": [
    0.59683,
    0.00275,
    0.78224,
    0.17857
  ],
  "Wing_Finger.001.L": [
    0.74151,
    -0.06975,
    0.62245,
    0.24052
  ],
  "Wing_Finger.002.L": [
    -0.94189,
    0,
    -0.24094,
    0.23407
  ],
  "Wing_Finger.003.L": [
    -0.92056,
    0,
    -0.3248,
    0.21697
  ],
  "Wing_Finger.004.L": [
    0.75679,
    -0.07016,
    0.61612,
    0.20672
  ],
  "Wing_Finger.005.L": [
    -0.94043,
    0,
    -0.28035,
    0.19236
  ],
  "Wing_Finger.006.L": [
    -0.99617,
    0,
    0.07662,
    0.04203
  ],
  "Wing_Finger.007.L": [
    0.76406,
    -0.07106,
    0.61829,
    0.16992
  ],
  "Wing_Finger.008.L": [
    -0.95041,
    0,
    -0.23239,
    0.20669
  ],
  "Wing_Finger.009.L": [
    0.38384,
    0,
    0.92301,
    0.02664
  ],
  "Wing_Finger.010.L": [
    0.78251,
    -0.0594,
    0.60502,
    0.1345
  ],
  "Wing_Finger.011.L": [
    -0.97333,
    0,
    -0.06897,
    0.21878
  ],
  "Wing_Finger.012.L": [
    0.77383,
    0,
    0.63142,
    0.04999
  ],
  "Wing_Finger.013.L": [
    0.8177,
    -0.04338,
    0.56578,
    0.09687
  ],
  "Wing_Finger.014.L": [
    -0.96478,
    0,
    0.16048,
    0.20842
  ],
  "Wing_Finger.015.L": [
    0.92978,
    0,
    0.36295,
    0.06141
  ],
  "Wing_Finger.016.L": [
    0.97985,
    -0.04395,
    0.18774,
    0.05209
  ],
  "Wing_Finger.017.L": [
    -0.40006,
    0,
    0.89434,
    0.20027
  ],
  "Wing_Finger.018.L": [
    0.73096,
    0,
    -0.67849,
    0.07316
  ],
  "Wing_Shoulder.R": [
    -0.56536,
    0.00185,
    -0.46205,
    0.68329
  ],
  "Wing_UpperArm.R": [
    0.24658,
    -0.01642,
    -0.50809,
    0.82509
  ],
  "Wing_Forearm.R": [
    0.59683,
    -0.00275,
    -0.78224,
    0.17857
  ],
  "Wing_Finger.001.R": [
    0.74151,
    0.06975,
    -0.62245,
    0.24052
  ],
  "Wing_Finger.002.R": [
    -0.94189,
    0,
    0.24094,
    0.23407
  ],
  "Wing_Finger.003.R": [
    -0.92056,
    0,
    0.3248,
    0.21697
  ],
  "Wing_Finger.004.R": [
    0.75679,
    0.07016,
    -0.61612,
    0.20672
  ],
  "Wing_Finger.005.R": [
    -0.94043,
    0,
    0.28035,
    0.19236
  ],
  "Wing_Finger.006.R": [
    -0.99617,
    0,
    -0.07662,
    0.04203
  ],
  "Wing_Finger.007.R": [
    0.76406,
    0.07106,
    -0.61829,
    0.16992
  ],
  "Wing_Finger.008.R": [
    -0.95041,
    0,
    0.23239,
    0.20669
  ],
  "Wing_Finger.009.R": [
    0.38384,
    0,
    -0.92301,
    0.02664
  ],
  "Wing_Finger.010.R": [
    0.78251,
    0.0594,
    -0.60502,
    0.1345
  ],
  "Wing_Finger.011.R": [
    -0.97333,
    0,
    0.06897,
    0.21878
  ],
  "Wing_Finger.012.R": [
    0.77383,
    0,
    -0.63142,
    0.04999
  ],
  "Wing_Finger.013.R": [
    0.8177,
    0.04338,
    -0.56578,
    0.09687
  ],
  "Wing_Finger.014.R": [
    -0.96478,
    0,
    -0.16048,
    0.20842
  ],
  "Wing_Finger.015.R": [
    0.92978,
    0,
    -0.36295,
    0.06141
  ],
  "Wing_Finger.016.R": [
    0.97985,
    0.04395,
    -0.18774,
    0.05209
  ],
  "Wing_Finger.017.R": [
    -0.40006,
    0,
    -0.89434,
    0.20027
  ],
  "Wing_Finger.018.R": [
    0.73096,
    0,
    0.67849,
    0.07316
  ]
};
